# ==================== JVM ====================
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# ==================== Производительность ====================
org.gradle.parallel=true
org.gradle.caching=true
# Configuration Cache отключен, так как в связке AGP 9.3 + KSP 2.3 он вызывает сбои трансформаций
org.gradle.configuration-cache=false 

# ==================== AndroidX и Kotlin ====================
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.incremental=true

# ==================== AGP 9 + KSP ====================
android.builtInKotlin=false
android.disallowKotlinSourceSets=false
ksp.useKSP2=true

# ==================== ПРОКСИ ====================
systemProp.http.proxyHost=172.20.20.8
systemProp.http.proxyPort=8080
systemProp.https.proxyHost=172.20.20.8
systemProp.https.proxyPort=8080