# ==================== JVM ====================
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# ==================== Производительность ====================
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

# Configuration cache (Gradle 8+)
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

# ==================== AndroidX ====================
android.useAndroidX=true
android.nonTransitiveRClass=true

# ==================== Kotlin ====================
kotlin.code.style=official
kotlin.incremental=true

# ==================== Build Features ====================
android.nonFinalResIds=false

systemProp.http.proxyHost=172.20.20.8
systemProp.http.proxyPort=8080
systemProp.https.proxyHost=172.20.20.8
systemProp.https.proxyPort=8080